local_repository(
    name = "io_bazel_rules_dotnet",
    path = "../..",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "dotnet_nuget_new",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
)

dotnet_register_toolchains()

dotnet_repositories_nugets()

dotnet_nuget_new(
    name = "grpc.core.runtime",
    build_file_content = """exports_files(glob(["runtimes/**/*"]), visibility = ["//visibility:public"])""",
    package = "grpc.core",
    sha256 = "b625817b7e8dfe66e0894b232001b4c2f0e80aa41dc4dccb59d5a452ca36a755",
    version = "2.28.1",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# GRPC
http_archive(
    name = "rules_proto_grpc",
    # sha256 = "5f0f2fc0199810c65a2de148a52ba0aff14d631d4e8202f41aff6a9d590a471b",
    strip_prefix = "rules_proto_grpc-3.1.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/3.1.0.tar.gz"],
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_repos")
rules_proto_grpc_toolchains()
rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

load("@rules_proto_grpc//csharp:repositories.bzl", rules_proto_grpc_csharp_repos = "csharp_repos")
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
load("@rules_proto_grpc//csharp/nuget:nuget.bzl", "nuget_rules_proto_grpc_packages")

rules_proto_grpc_csharp_repos()
grpc_deps()
nuget_rules_proto_grpc_packages()


# load NUGET deps
load("//:gen/nuget.bzl", "project_dotnet_repositories_nuget")

project_dotnet_repositories_nuget()
